name: Pull Request - Lint/Build/Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pull_request:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm ci
      - uses: nrwl/nx-set-shas@v4
      - run: npx playwright install --with-deps
      - run: npx nx affected -t lint test build
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: react-spa playwright-report
          path: |
            examples/react-spa/playwright-report/
            examples/react-spa/test-results/
          retention-days: 7
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: preact-spa playwright-report
          path: |
            examples/preact-spa/playwright-report/
            examples/preact-spa/test-results/
          retention-days: 7
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: nextjs-spa playwright-report
          path: |
            examples/nextjs-spa/playwright-report/
            examples/nextjs-spa/test-results/
          retention-days: 7
      - uses: chromaui/action@v11.7.0
        env:
          DEBUG: vite:resolve-details
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      - if: always()
        uses: actions/upload-artifact@v2
        with:
          # upload build log
          name: chromatic
          path: build-storybook.log
